### ISSUE TITLE
Memory stats wildly inaccurate on Ubuntu 15.10 beta 2

### ISSUE THREAD

**Issue by Phaestion** [fossfreedom/indicator-sysmonitor#36]
Hi there 

I recently tried out Ubuntu 15.10 beta 2. The memory indicator is way off, stating that I am using 90% of my RAM where System Monitor shows that I am in fact only using 31% of my RAM.

I searched the issues, but could not find anything regarding this issue.

Regards

**Comment by fossfreedom** [comment]
The code is in sensors.py

Have a look at line 388 onwards:

<pre>
if (minor_version >= 16 and major_version == 3) or (major_version > 3):
                meminfo.readline()
                available = SensorManager.digit_regex.findall(
                    meminfo.readline()).pop()
                return 100 - 100 * int(available) / float(total)
            else:
                free = SensorManager.digit_regex.findall(
                    meminfo.readline()).pop()
                meminfo.readline()
                cached = SensorManager.digit_regex.findall(
                    meminfo.readline()).pop()
                free = int(free) + int(cached)
                return 100 - 100 * free / float(total)

</pre>

**Comment by fossfreedom** [comment]
please can you give me the output of:

    cat /proc/meminfo

when you see the odd figures - the calculation should be the "100 - (100 * (mem available / mem total))"

**Comment by Phaestion** [comment]
Hi there

It makes sense that the above commands should produce the correct output, but alas it doesn't. I'll have to get the project going on my system to debug a bit, when I have some free time. In the meanwhile:

Here is the output of cat /proc/meminfo
```
MemTotal:       11734076 kB
MemFree:         4755620 kB
MemAvailable:    6939400 kB
Buffers:          533372 kB
Cached:          2262952 kB
SwapCached:            0 kB
Active:          4843452 kB
Inactive:        1635692 kB
Active(anon):    3715772 kB
Inactive(anon):   802248 kB
Active(file):    1127680 kB
Inactive(file):   833444 kB
Unevictable:         392 kB
Mlocked:             392 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:              1168 kB
Writeback:             0 kB
AnonPages:       3682700 kB
Mapped:           631376 kB
Shmem:            835204 kB
Slab:             334332 kB
SReclaimable:     273776 kB
SUnreclaim:        60556 kB
KernelStack:       13856 kB
PageTables:        61660 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     5867036 kB
Committed_AS:   12793504 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      373332 kB
VmallocChunk:   34358947836 kB
HardwareCorrupted:     0 kB
AnonHugePages:    739328 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      271692 kB
DirectMap2M:     9635840 kB
DirectMap1G:     2097152 kB
```
The memory usage is wrong all of the time. See attached screenshot.
![screenshot from 2015-10-07 08-22-01](https://cloud.githubusercontent.com/assets/1764844/10330499/90f92dfe-6ccd-11e5-8a1c-76b03ac8fc5b.png)

**Comment by fossfreedom** [comment]
it looks very much like the previous commit in this area mistakenly pulled the memfree value instead of the memavailable value from the list.

This bit of  code is just asking for trouble assuming the order of return is the same all the time.

Probably better to "grep" through the /proc/meminfo list for the actual lines containing the strings "MemAvailable" and "MemTotal" so that we can be confident that the values pulled are accurate

implement python grep something along the lines of this

 - http://stackoverflow.com/questions/1921894/grep-and-python

**Comment by fossfreedom** [comment]
@Phaestion 

  the above commit should fix this hopefully.

**Comment by toyongbanatero** [comment]
Sorry to comment here, but I'm still experiencing this issue on Ubuntu 15.10. Everything was okay before the upgrade, but in Wily, everything was reported way wrong. On startup after login, the memory values are correct, but after some time, it stays at above 90% when in truth, I was using only about 50%.
I've seen above that the issue looks fixed on a commit, but when will the update be rolled out?
(I'm also thinking why the problem is in code, when in fact, I haven't experienced this on 15.04 but only after I upgraded to 15.10 which is about several days ago and the last update listed in Launchpad was 4 weeks ago and I haven't experienced this back that time.)

**Comment by fossfreedom** [comment]
@toyongbanatero 

  I've been a bit busy with other projects.  I'll try to push out a PPA update later this week.

This appears to be a kernel issue - 15.04 uses v3.19 whereas 15.10 used 4.2
